Get multiple paged charges by target Id endpoint.
LBHackney-IT/charges-api pull request #144
Opened 2022-10-28 08:36 UTC by Duslerke

# What:
 - An endpoint for retrieving multiple paged detailed charges by target Id.

# Why:
 - There is a need for them to be searched by Asset Id. Presumably Hackney staff need to see charges associated with the property.

2022-10-28 14:38 UTC, FaisalHackney requested changes

2022-10-28 14:38 UTC, FaisalHackney commented on ChargesApi/V1/Gateways/PostgreGateway.cs
> +        public async Task<IEnumerable<DetailedChargeDomain>> GetPageOfChargesAsync(GetPagedChargesSearchParametersDomain searchParams)
Could you remove "Async" from the end of method names for methods which are asynchonrous in any case

2022-10-28 14:38 UTC, FaisalHackney commented on ChargesApi/V1/Gateways/PostgreGateway.cs
> +        public async Task<int> GetPagedChargesTotalCountAsync(GetPagedChargesSearchParametersDomain searchParams)
Remove "Async" from method name

2022-10-28 14:38 UTC, FaisalHackney commented on ChargesApi/V1/Domain/ParameterWrappers/GetPagedChargesSearchParametersDomain.cs
> +    public class GetPagedChargesSearchParametersDomain
Could this class name be renamed to something shorter and more descriptive:

This is about Paging per se and is not Charge-specific
Consider renaming to: `PageParameters`

2022-10-28 14:38 UTC, FaisalHackney commented on ChargesApi/V1/Boundary/Request/GetPagedChargesParametersPresentation.cs
> +    public class GetPagedChargesSearchParametersPresentation
This should be renamed without Charges in the name - as it is about paging and is not specific to Charges

It is the same as is Domain layer counterpart and should have the same name. 
Consider renaming to: PageParameters

We know it is in the Presentation layer by its namespace. No need to add "Presentation" in the name.

2022-10-28 14:38 UTC, FaisalHackney commented on ChargesApi/V1/Boundary/Response/GetPagedChargesByTargetIdResponse.cs
> +    public class GetPagedChargesByTargetIdResponse
Rename to `PagedResultsResponse` ?

2022-10-28 16:27 UTC, Duslerke commented on ChargesApi/V1/Boundary/Request/GetPagedChargesParametersPresentation.cs
> +    public class GetPagedChargesSearchParametersPresentation
We add the layer information into the type name so that we wouldn't have to specify the types names using namespaces to avoid a name conflict (pretty much to avoid stuff like this: `Domain.EndpointNameParameters` or `Boundary.Requests.EndpointNameParameters`. Places there this would need to be used are all the factory methods & unit tests. Having a layer name in the type name also allows to read method signatures easier without the need to mouse-over and wait for the intellisense to determine the namespace.

I did, however, extract the page parameters.

2022-11-10 10:06 UTC, FaisalHackney approved these changes

2022-11-10 10:06 UTC, FaisalHackney commented on ChargesApi/V1/Factories/ParameterWrapperFactory.cs
> +namespace ChargesApi.V1.Factories
This is good!

2022-11-10 10:07 UTC, merged